module.exports = {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-order"],
  rules: {
    "order/properties-order": [
      [
        {
          groupName: "custom-properties",
          properties: ["/^--/"],
        },
        {
          groupName: "positioning",
          properties: [
            "position",
            "z-index",
            "inset",
            "inset-block",
            "inset-block-start",
            "inset-block-end",
            "inset-inline",
            "inset-inline-start",
            "inset-inline-end",
            "top",
            "right",
            "bottom",
            "left",
          ],
        },
        {
          groupName: "layout",
          properties: [
            "display",
            "visibility",
            "overflow",
            "overflow-x",
            "overflow-y",
            "clip",
            "clip-path",
            "object-fit",
            "object-position",
            "flex",
            "flex-grow",
            "flex-shrink",
            "flex-basis",
            "flex-direction",
            "flex-wrap",
            "grid",
            "grid-template",
            "grid-template-areas",
            "grid-template-columns",
            "grid-template-rows",
            "grid-auto-flow",
            "grid-auto-columns",
            "grid-auto-rows",
            "grid-column",
            "grid-column-start",
            "grid-column-end",
            "grid-row",
            "grid-row-start",
            "grid-row-end",
            "gap",
            "row-gap",
            "column-gap",
            "place-items",
            "place-content",
            "place-self",
            "align-items",
            "align-content",
            "align-self",
            "justify-items",
            "justify-content",
            "justify-self",
          ],
        },
        {
          groupName: "sizing",
          properties: [
            "box-sizing",
            "inline-size",
            "block-size",
            "min-inline-size",
            "min-block-size",
            "max-inline-size",
            "max-block-size",
            "width",
            "min-width",
            "max-width",
            "height",
            "min-height",
            "max-height",
            "aspect-ratio",
          ],
        },
        {
          groupName: "spacing",
          properties: [
            "margin",
            "margin-block",
            "margin-block-start",
            "margin-block-end",
            "margin-inline",
            "margin-inline-start",
            "margin-inline-end",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "padding",
            "padding-block",
            "padding-block-start",
            "padding-block-end",
            "padding-inline",
            "padding-inline-start",
            "padding-inline-end",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
          ],
        },
        {
          groupName: "border",
          properties: [
            "border",
            "border-block",
            "border-block-start",
            "border-block-end",
            "border-inline",
            "border-inline-start",
            "border-inline-end",
            "border-top",
            "border-right",
            "border-bottom",
            "border-left",
            "border-width",
            "border-style",
            "border-color",
            "border-radius",
            "outline",
            "outline-width",
            "outline-style",
            "outline-color",
            "outline-offset",
          ],
        },
        {
          groupName: "background",
          properties: [
            "background",
            "background-color",
            "background-image",
            "background-size",
            "background-position",
            "background-repeat",
            "background-origin",
            "background-clip",
            "background-attachment",
            "filter",
            "backdrop-filter",
            "box-shadow",
            "opacity",
          ],
        },
        {
          groupName: "typography",
          properties: [
            "color",
            "font",
            "font-family",
            "font-size",
            "font-weight",
            "font-style",
            "line-height",
            "letter-spacing",
            "text-align",
            "text-transform",
            "text-decoration",
            "text-rendering",
            "white-space",
            "word-break",
            "overflow-wrap",
          ],
        },
        {
          groupName: "interaction",
          properties: [
            "appearance",
            "cursor",
            "pointer-events",
            "user-select",
            "touch-action",
          ],
        },
        {
          groupName: "animation",
          properties: [
            "transition",
            "transition-property",
            "transition-duration",
            "transition-timing-function",
            "transition-delay",
            "transform",
            "transform-origin",
            "animation",
            "animation-name",
            "animation-duration",
            "animation-timing-function",
            "animation-delay",
            "animation-iteration-count",
          ],
        },
      ],
      {
        unspecified: "bottomAlphabetical",
      },
    ],

    "alpha-value-notation": "number",
    "color-function-notation": "modern",
    "hue-degree-notation": "number",

    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-duplicate-custom-properties": null,
    "no-descending-specificity": null,
    "selector-id-pattern": null,
    "custom-property-empty-line-before": null,

    "selector-class-pattern":
      "^(u|c|l|is)-[a-z0-9]+(?:-[a-z0-9]+)*(?:__(?:[a-z0-9]+(?:-[a-z0-9]+)*))?(?:--(?:[a-z0-9]+(?:-[a-z0-9]+)*))?$",
  },
};
